#全局相关变量集----------------------
url: http://localhost:4000 #http://ifengwang.github.io/blog
#baseurl: /blog
encoding: utf-8



#页面相关变量集----------------------







#作者相关变量集----------------------
author: Frank